#!/bin/bash

if [ -z $1 ]; then
    echo "Usage: $0 <Model Name>"
    echo "<Model Name> is mandatory" 
    exit 1
fi

MODELNAME=$1
CONFIGFILE="aws-deepracer.cf"

if [ -f $CONFIGFILE ]; then
    ACCOUNTID=$(grep -i ACCOUNTID $CONFIGFILE | awk -F= '{gsub(/"/, "", $2); print $2}')
else
    echo "The config file $CONFIGFILE is not found"
    exit 1
fi

SEASON="season-$(date +%Y-%m)"

DATA='{"headers":{"X-Amz-User-Agent":"aws-sdk-js/2.324.0 promise","Content-Type":"application/x-amz-json-1.1","X-Amz-Target":"AwsSilverstoneCloudService.CreateLeaderboardSubmission"},"path":"/","method":"POST","region":"us-east-1","params":{},"contentString":"{\"LeaderboardArn\":\"arn:aws:deepracer:us-east-1::leaderboard/'
DATA+=$SEASON
DATA+='\",\"ModelArn\":\"arn:aws:deepracer:us-east-1:'
DATA+=$ACCOUNTID
DATA+=':model/reinforcement_learning/'
DATA+=$MODELNAME
DATA+='\"}","operation":"createLeaderboardSubmission"}'
export DATA

./aws-execCurl | jq '.'
