#!/bin/bash

SEASON="season-$(date +%Y-%m)"
DRUSER=""
DATASEASON='{"headers":{"X-Amz-User-Agent":"aws-sdk-js/2.324.0 promise","Content-Type":"application/x-amz-json-1.1","X-Amz-Target":"AwsSilverstoneCloudService.ListLeaderboardSubmissions"},"path":"/","method":"POST","region":"us-east-1","params":{},"contentString":"{\"LeaderboardArn\":\"'

function usage {
  echo "Usage: `basename $0` -s [season-yyyy-mm|community race name] -u username -c"
  echo "-s if it is not used, the race name is set to season-<current year>-<current-month>"
  echo "-c is optional for community race"
}

c_flag=0
while getopts "cs:u:" opt; do
  case "$opt" in
  c)
    c_flag=1
    ;;
  s)
    SEASONX=(${OPTARG//-/ })
    if [ "${SEASONX[0]}" -eq "${SEASONX[0]}" ] 2>/dev/null
    then
      SEASON="season-$OPTARG"
    else
      SEASON="$OPTARG"
    fi
    ;;
  u)  DRUSER=$OPTARG
    ;;
  \?)
    usage
    exit
    ;;
  esac
done

if [ $c_flag -eq 1 ]; then
  ARN=$(./aws-listSubscribedPrivateLeaderboards |jq '.PrivateLeaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
else
  ARN=$(./aws-listLeaderboards |jq '.Leaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
fi

if [ -z "$ARN" ]; then
  echo '{ "error": [ "'$SEASON' does not exist" ] }'
  exit 1
fi

DATASEASON="$DATASEASON$ARN"

DATA=$DATASEASON'\",\"MaxResults\":100}","operation":"listLeaderboardSubmissions"}'
export DATA

counter=0
./aws-execCurl | jq '.' > .curl.result.$counter
NextToken=$(jq '.NextToken' .curl.result.$counter | sed 's/"/\\"/g')
LeaderBoard=$(jq '.LeaderboardSubmissions' .curl.result.$counter)
while [ $NextToken != 'null' ]; do
  DATA=$DATASEASON'\",\"MaxResults\":100,\"NextToken\":'$NextToken'}","operation":"listLeaderboardSubmissions"}'
  export DATA
  counter=$(( $counter+1 ))
  ./aws-execCurl | jq '.' > .curl.result.$counter
  NextToken=$(jq '.NextToken' .curl.result.$counter | sed 's/"/\\"/g')
  LeaderBoard="$LeaderBoard $(jq '.LeaderboardSubmissions' .curl.result.$counter)"
done

rm .curl.result.*
if [ -z $DRUSER ]; then
  echo $LeaderBoard | jq -s add
else
  echo $LeaderBoard | jq -s 'add[]|select(.Alias == "'$DRUSER'")'
fi 
