#!/bin/bash

SEASON="season-$(date +%Y-%m)"
DRUSER=""

while getopts "s:u:" opt; do
  case "$opt" in
  s)
    SEASON="season-$OPTARG"
    ;;
  u)  DRUSER=$OPTARG
    ;;
  \?)
    echo "Usage: `basename $0` -s yyyy-mm -u username"
    exit
    ;;
  esac
done

DATASEASON='{"headers":{"X-Amz-User-Agent":"aws-sdk-js/2.324.0 promise","Content-Type":"application/x-amz-json-1.1","X-Amz-Target":"AwsSilverstoneCloudService.ListLeaderboardSubmissions"},"path":"/","method":"POST","region":"us-east-1","params":{},"contentString":"{\"LeaderboardArn\":\"arn:aws:deepracer:us-east-1::leaderboard/'
DATASEASON+=$SEASON

DATA=$DATASEASON'\",\"MaxResults\":100}","operation":"listLeaderboardSubmissions"}'
export DATA

counter=0
./aws-execCurl | jq '.' > .curl.result.$counter
NextToken=$(jq '.NextToken' .curl.result.$counter | sed 's/"/\\"/g')
LeaderBoard=$(jq '.LeaderboardSubmissions' .curl.result.$counter)
while [ $NextToken != 'null' ]; do
  DATA=$DATASEASON'\",\"MaxResults\":100,\"NextToken\":'$NextToken'}","operation":"listLeaderboardSubmissions"}'
  export DATA
  counter=$(( $counter+1 ))
  ./aws-execCurl | jq '.' > .curl.result.$counter
  NextToken=$(jq '.NextToken' .curl.result.$counter | sed 's/"/\\"/g')
  LeaderBoard="$LeaderBoard $(jq '.LeaderboardSubmissions' .curl.result.$counter)"
done
rm .curl.result.*
if [ -z $DRUSER ]; then
  echo $LeaderBoard | jq -s add
else
  echo $LeaderBoard | jq -s 'add[]|select(.Alias == "'$DRUSER'")'
fi 
