#!/bin/bash

if [ -z $1 ]; then
    SEASON="season-$(date +%Y-%m)"
else
    SEASON="season-$1"
fi

DATA='{"headers":{"X-Amz-User-Agent":"aws-sdk-js/2.324.0 promise","Content-Type":"application/x-amz-json-1.1","X-Amz-Target":"AwsSilverstoneCloudService.GetRankedUserSubmission"},"path":"/","method":"POST","region":"us-east-1","params":{},"contentString":"{\"LeaderboardArn\":\"arn:aws:deepracer:us-east-1::leaderboard/'
DATA+=$SEASON
DATA+='\"}","operation":"getRankedUserSubmission"}'
export DATA

./aws-execCurl | jq '.'
