#!/bin/bash

if [ -z $1 ]; then
    SEASON="season-$(date +%Y-%m)"
else
    SEASON="season-$1"
fi

SEASON="season-$(date +%Y-%m)"
DATASEASON='{"headers":{"X-Amz-User-Agent":"aws-sdk-js/2.324.0 promise","Content-Type":"application/x-amz-json-1.1","X-Amz-Target":"AwsSilverstoneCloudService.GetRankedUserSubmission"},"path":"/","method":"POST","region":"us-east-1","params":{},"contentString":"{\"LeaderboardArn\":\"'

c_flag=0
while getopts "cs:" opt; do
  case "$opt" in
  c)
    c_flag=1
    ;;
  s)
    SEASONX=(${OPTARG//-/ })
    if [ "${SEASONX[0]}" -eq "${SEASONX[0]}" ] 2>/dev/null
    then
      SEASON="season-$OPTARG"
    else
      SEASON="$OPTARG"
    fi
    ;;
  \?)
    echo "Usage: `basename $0` -s [season-yyyy-mm|community race name] -c"
    echo "-c is optional for community race"
    exit
    ;;
  esac
done

if [ $c_flag -eq 1 ]; then
  ARN=$(./aws-listSubscribedPrivateLeaderboards |jq '.PrivateLeaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
else
  ARN=$(./aws-listLeaderboards |jq '.Leaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
fi

if [ -z "$ARN" ]; then
  echo '{ "error": [ "'$SEASON' does not exist" ] }'
  exit 1
fi

DATASEASON="$DATASEASON$ARN"
DATA=$DATASEASON'\"}","operation":"getRankedUserSubmission"}'
export DATA

./aws-execCurl | jq '.'
