#!/bin/bash

DATA='{"headers":{"X-Amz-User-Agent":"aws-sdk-js/2.324.0 promise","Content-Type":"application/x-amz-json-1.1","X-Amz-Target":"AwsSilverstoneCloudService.ListModels"},"path":"/","method":"POST","region":"us-east-1","params":{},"contentString":"{\"ModelType\":\"REINFORCEMENT_LEARNING\",\"MaxResults\":100}","operation":"listModels"}'
export DATA

./aws-execCurl | jq '.'
